### ISSUE TITLE
Value network

### ISSUE THREAD

**Issue by jendelel** [pranz24/pytorch-soft-actor-critic#9]
Hi, 

I skimmed over the author's implementation and it seems that they don't use the value network. Instead they only use the Q-networks. Seems they removed it in [this commit](https://github.com/rail-berkeley/softlearning/commit/d33c114816429c494e2a40625849d57ae2103f3f#diff-1c64d7ee5ec9fc6ed8210fb75352123f)

Thanks, 

Lukas

**Comment by pranz24** [comment]
Hmm... 
You are correct the author's don't use a value function
[https://arxiv.org/pdf/1812.05905.pdf](https://arxiv.org/pdf/1812.05905.pdf) -> automatic entropy tuning
Although, they did use it in their earlier paper [https://arxiv.org/pdf/1801.01290.pdf](https://arxiv.org/pdf/1801.01290.pdf) -> Maybe that's why I never removed it

I agree with you, that we should remove the value function.
It will also make [sac.py](https://github.com/pranz24/pytorch-soft-actor-critic/blob/master/sac.py) a bit cleaner. (Since we anyway don't use a value function in the deterministic case)

I have made some minor changes in the repo. (Nothing major -> Just changing variable names)

You are free to make a PR regarding this issue whenever you want.

**Comment by pranz24** [comment]
Or I'll make the changes.
Whatever is fine with you.

**Comment by jendelel** [comment]
I already made the changes in my [repo](https://github.com/jendelel/rhl-algs/blob/master/sac2.py). You can copy it from there or I can send you a pull request. As you want :)

**Comment by pranz24** [comment]
Got it. :+1: 
I'll make the changes. :grin:
